CREATE TABLE [dbo].[Answer]
(
	[AnswerId] INT IDENTITY(1,1) PRIMARY KEY,
	[Content] NVARCHAR(max) NOT NULL,
	[UserId] NVARCHAR(150) NOT NULL,
	[UserName] NVARCHAR(150) NOT NULL,
	[Created] DATETIME2(7) NOT NULL,
	[QuestionId] INT NOT NULL FOREIGN KEY REFERENCES [dbo].[Question]([QuestionId])
	ON UPDATE CASCADE
	ON DELETE CASCADE
)
